# Generated by Django 3.2 on 2021-07-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('rollno', models.IntegerField()),
                ('Mobileno', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
